import 'package:flutter/material.dart';

class ScreenSliver extends StatelessWidget {
  const ScreenSliver({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: CustomScrollView(
          slivers: [
            SliverAppBar(
              title: Row(
                children: [
                  CircleAvatar(),
                  Spacer(),
                  Icon(Icons.ac_unit),
                  Icon(Icons.ac_unit),
                ],
              ),
              pinned: true,
              expandedHeight: 200,
              backgroundColor: Colors.black.withOpacity(0.85),
              // bottom: PreferredSize(preferredSize: Size.fromHeight(100), child: Column())
              flexibleSpace: FlexibleSpaceBar(
                background: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    Text("abc"),
                    Text("abc"),
                    Text("abc"),

                  ],
                ),
              ),
            ),
            SliverToBoxAdapter(
              child: Column(
                children: [
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                  Text("hjbsdjkldsvdniovd"),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
